apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_NAME}
  namespace: ${ENVIRONMENT}
spec:
  selector:
    matchLabels:
      app: ${APP_NAME}
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0
    type: RollingUpdate
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: ${APP_NAME}
      annotations:
        prometheus.io/scrape: "true"
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    spec:
      # Affinity to make sure that multiple pods does not run on the same node
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            # prefer to run in different data centres
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - ${APP_NAME}
                topologyKey: failure-domain.beta.kubernetes.io/zone
            # prefer to run on different "physical" nodes
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - ${APP_NAME}
                topologyKey: kubernetes.io/hostname
      nodeSelector:
        cloud.google.com/gke-spot: "true"
      terminationGracePeriodSeconds: 25
      containers:
        - name: container
          image: ${DOCKER_IMAGE}
          resources:
            limits:
              cpu: "${APP_CPU_LIMIT}m"
              memory: "${APP_MEM_LIMIT}Mi"
            requests:
              cpu: "${APP_CPU_REQUEST}m"
              memory: "${APP_MEM_REQUEST}Mi"
          envFrom:
            - configMapRef:
                name: ${APP_NAME}-config
            - secretRef:
                name: ${APP_NAME}-secret-values
          ports:
            - containerPort: ${APP_PORT}
              name: http-port
          livenessProbe:
            httpGet:
              path: /_healthz
              port: http-port
            initialDelaySeconds: 120
            timeoutSeconds: 10
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /_healthz
              port: http-port
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 2
          volumeMounts:
            - name: secret-files-volume
              mountPath: /app/secret-files
              readOnly: true
      volumes:
        - name: secret-files-volume
          secret:
            secretName: ${APP_NAME}-secret-files
---
apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}-load-balancer
  namespace: ${ENVIRONMENT}
spec:
  type: LoadBalancer
  selector:
    app: ${APP_NAME}
  ports:
    - port: 80
      protocol: TCP
      targetPort: http-port
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ${APP_NAME}-hpa
  namespace: ${ENVIRONMENT}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${APP_NAME}
  minReplicas: ${APP_MIN_REPLICAS}
  maxReplicas: ${APP_MAX_REPLICAS}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
